import type { CategoryData } from "./categoryTypes";

export const EXTRA_CATEGORIES: Record<string, CategoryData> = {
  estetica: {
    slug: "consorcio-estetica",
    name: "Consórcio para Estética",
    shortName: "Estética",
    heroTitle: "Consórcio para Estética",
    heroAccent: "Sem Juros",
    heroSubtitle:
      "Harmonização, odontologia estética, procedimentos de beleza com parcelas fixas e zero juros como empréstimo bancário.",
    heroImage: "/items/estetica.jpg",
    metaTitle: "Consórcio para Estética Sem Juros | Harmonização e Autocuidado",
    metaDescription:
      "Consórcio de estética 100% sem juros. Harmonização facial, odontologia, procedimentos com carta Servopa e Rodobens. Simule grátis na Lacosta.",
    ogTitle: "Consórcio para Estética Sem Juros | Lacosta Consórcios",
    ogDescription:
      "Realize seus procedimentos de beleza sem financiar no cartão. Parcelas sem juros com administradoras oficiais.",
    calculatorCategory: "estetica",
    avgSaving: "R$ 15.000",
    introTitle: "Por que consórcio para estética e autocuidado?",
    introText:
      "Financiamentos em clínicas ou parcelamentos no cartão carregam juros altos. No consórcio, você acumula crédito com taxa de administração conhecida e, contemplado, usa a carta para pagar seus procedimentos com poder de negociação. Ideal para quem planeja harmonização, implantes ou tratamentos de maior valor.",
    problemTitle: "O custo do cartão e do crédito informal",
    problemText:
      "Um procedimento de R$ 25.000 parcelado no cartão em 24x pode gerar R$ 35.000 ou mais no total. Em muitos casos você paga juros que não aparecem de forma clara, mas estão embutidos na parcela.",
    solutionTitle: "Consórcio: planejamento com valor transparente",
    solutionText:
      "No consórcio você sabe a taxa de administração desde o início. Sem juros compostos. Você escolhe o valor da carta, participa dos sorteios e lances, e quando contemplado usa o crédito para fechar seus procedimentos negociando melhor à vista.",
    comparison: [
      { label: "Procedimento (ex.)", financing: "R$ 25.000", consortium: "R$ 25.000", winner: "tie" },
      { label: "Encargos típicos", financing: "Juros altos / rotativo", consortium: "Só taxa admin", winner: "consortium" },
      { label: "Total estimado 24x", financing: "R$ 35.000+", consortium: "R$ 29.500*", winner: "consortium" },
      { label: "Negociar pacote à vista", financing: "Difícil", consortium: "Sim", winner: "consortium" },
      { label: "Limite de cartão", financing: "Consome fatura", consortium: "Não depende do cartão", winner: "consortium" },
      { label: "Planejamento de longo prazo", financing: "Curto", consortium: "Sim", winner: "consortium" },
    ],
    comparisonNote: "*Exemplo ilustrativo com taxa de administração diluída. Valores e grupos variam conforme produto Servopa ou Rodobens.",
    steps: [
      { title: "Simule grátis", description: "Defina o valor aproximado dos procedimentos e veja parcelas possíveis." },
      { title: "Escolha o plano", description: "Consultor indica o grupo de consórcio mais alinhado ao seu objetivo e prazo." },
      { title: "Contemplação", description: "Sorteio mensal ou lance para antecipar a carta de crédito." },
      { title: "Realize os procedimentos", description: "Use a carta com clínicas credenciadas ou conforme regra do grupo." },
    ],
    theme: {
      accent: "#E11D48",
      accentLight: "#FB7185",
      accentRgb: "225,29,72",
      gradient: "linear-gradient(135deg, #BE123C 0%, #E11D48 100%)",
      darkBg: "linear-gradient(180deg, #2C0A14 0%, #4C0519 50%, #2C0A14 100%)",
      benefitsLayout: "grid",
      comparisonStyle: "cards",
      stepsStyle: "timeline",
    },
    ctaHeadline: "Quero meus procedimentos sem juros de cartão",
    ctaSub: "Descubra em 30 segundos a parcela da sua harmonização, implante ou tratamento.",
    ctaStats: "Ver quanto eu economizo nos procedimentos",
    ctaFeatures: "Qual procedimento você quer realizar? Simule o valor.",
    ctaSteps: "Planejar meus procedimentos agora",
    benefits: [
      { title: "Parcelas previsíveis", description: "Sem surpresa de juros rotativos. Você planeja o orçamento com clareza.", highlight: "Previsibilidade" },
      { title: "Procedimentos de alto valor", description: "Harmonização, odontologia e tratamentos completos em um só planejamento.", highlight: "Projetos de beleza" },
      { title: "Sem estourar o limite", description: "O consórcio não depende do limite do seu cartão de crédito.", highlight: "Crédito dedicado" },
      { title: "Assessoria Lacosta", description: "Ajudamos desde a simulação até a contemplação e uso da carta.", highlight: "Consultoria gratuita" },
      { title: "Administradoras fortes", description: "Grupos Servopa e Rodobens com tradição no mercado.", highlight: "Segurança Bacen" },
      { title: "Lance para antecipar", description: "Se fizer sentido no seu fluxo, lance acelera a contemplação.", highlight: "Flexibilidade" },
    ],
    faqs: [
      { question: "Posso usar consórcio de estética em qualquer clínica?", answer: "Depende das regras do grupo e da rede credenciada da administradora. Nossa equipe explica quais opções se aplicam ao seu caso e ao produto contratado." },
      { question: "Consórcio de estética tem juros?", answer: "Não há juros como em empréstimo ou rotativo. Há taxa de administração, prevista em contrato e diluída nas parcelas." },
      { question: "Qual o valor mínimo da carta?", answer: "Varia por grupo. Simule no site ou fale conosco para encontrar o plano compatível com o valor dos seus procedimentos." },
      { question: "Quanto tempo até a contemplação?", answer: "Há sorteios periódicos e possibilidade de lance. A média nos nossos grupos costuma ser competitiva; avaliamos junto com você." },
      { question: "Estética entra em consórcio de serviços?", answer: "Sim. Produtos de consórcio de serviços podem contemplar segmentos de saúde e estética. A Lacosta direciona você ao produto correto." },
    ],
    sectionOrder: ["features", "stats", "problem-solution", "comparison", "benefits", "steps", "faq", "cross-sell"],
    statsHighlight: [
      { value: "R$ 15 mil", label: "Economia no tratamento", description: "Comparado a parcelamento no cartão de crédito" },
      { value: "Até 40%", label: "Desconto à vista", description: "Clínicas oferecem desconto real para pagamento com carta" },
      { value: "0", label: "Juros do cartão", description: "Sem rotativo nem parcelas com juros embutidos" },
    ],
    featureTitle: "Procedimentos que a carta cobre",
    featureSubtitle: "Do sorriso novo à harmonização completa, planeje sem juros",
    featureCards: [
      { title: "Harmonização facial", description: "Preenchimento, botox, bichectomia e rinomodelação." },
      { title: "Implantes dentários", description: "Protocolo sobre implante, prótese fixa e enxerto ósseo." },
      { title: "Procedimentos corporais", description: "Lipoescultura, abdominoplastia e tratamentos estéticos avançados." },
      { title: "Odontologia estética", description: "Facetas, lentes de contato dental e clareamento profissional." },
      { title: "Tratamentos capilares", description: "Transplante capilar e terapias de recuperação." },
      { title: "Pacotes completos", description: "Combine procedimentos em um só planejamento financeiro." },
    ],
  },

  embarcacoes: {
    slug: "consorcio-embarcacoes",
    name: "Consórcio de Embarcações",
    shortName: "Embarcações",
    heroTitle: "Consórcio de Embarcações",
    heroAccent: "Sem Juros",
    heroSubtitle:
      "Lancha, barco, jet ski ou veleiro com carta de crédito sem juros bancários. Realize o sonho náutico com planejamento.",
    heroImage: "/items/embarcacao.png",
    metaTitle: "Consórcio de Embarcações Sem Juros | Lancha e Barco | Lacosta",
    metaDescription:
      "Consórcio náutico sem juros: lanchas, barcos, jet skis com Servopa e Rodobens. Simule grátis com a Lacosta Consórcios.",
    ogTitle: "Consórcio de Embarcações | Lacosta Consórcios",
    ogDescription: "Crédito para sua embarcação sem juros. Assessoria especializada em todo o Brasil.",
    calculatorCategory: "embarcacoes",
    avgSaving: "R$ 40.000",
    introTitle: "Por que consórcio para comprar embarcação?",
    introText:
      "O crédito náutico tradicional costuma ser caro e burocrático. O consórcio permite acumular crédito com parcelas sem juros de financiamento, e a carta amplia seu poder de negociação na compra do barco ou lancha, nova ou usada conforme regras do grupo.",
    problemTitle: "Financiamento náutico pesa no bolso",
    problemText:
      "Taxas elevadas e entrada são comuns em linhas de crédito para barcos. O custo total pode superar em muito o valor da embarcação ao longo dos anos.",
    solutionTitle: "Consórcio alinha sonho e orçamento",
    solutionText:
      "Sem juros, apenas taxa de administração. Você entra no grupo, paga parcelas definidas e concorre à contemplação para receber o valor da carta e quitar o bem desejado.",
    comparison: [
      { label: "Embarcação (ex.)", financing: "R$ 200.000", consortium: "R$ 200.000", winner: "tie" },
      { label: "Encargo principal", financing: "Juros + seguros", consortium: "Taxa admin", winner: "consortium" },
      { label: "Entrada costuma exigir?", financing: "Sim", consortium: "Não (regra do grupo)", winner: "consortium" },
      { label: "Negociação à vista", financing: "Raro", consortium: "Com carta, sim", winner: "consortium" },
      { label: "Previsibilidade", financing: "CET variável", consortium: "Contrato claro", winner: "consortium" },
      { label: "Regulamentação", financing: "Banco / financeira", consortium: "Bacen (consórcio)", winner: "tie" },
    ],
    comparisonNote: "Cenário ilustrativo. Condições reais dependem do produto, prazo e grupo escolhido.",
    steps: [
      { title: "Simule", description: "Estime o valor da embarcação e veja faixas de parcela." },
      { title: "Feche o plano", description: "Escolhemos com você o grupo Servopa ou Rodobens mais adequado." },
      { title: "Contemplação", description: "Sorteio ou lance conforme sua estratégia." },
      { title: "Retire a embarcação", description: "Utilize a carta conforme regulamento para aquisição." },
    ],
    theme: {
      accent: "#0891B2",
      accentLight: "#67E8F9",
      accentRgb: "8,145,178",
      gradient: "linear-gradient(135deg, #0E7490 0%, #0891B2 100%)",
      darkBg: "linear-gradient(180deg, #062028 0%, #083344 50%, #062028 100%)",
      benefitsLayout: "bento",
      comparisonStyle: "table",
      stepsStyle: "horizontal",
    },
    ctaHeadline: "Quero minha embarcação sem financiamento caro",
    ctaSub: "Simule a carta de crédito ideal para sua lancha, barco ou jet ski em 30 segundos.",
    ctaStats: "Calcular minha economia náutica",
    ctaFeatures: "Qual embarcação é o seu sonho? Veja a parcela.",
    ctaSteps: "Iniciar minha simulação náutica",
    benefits: [
      { title: "Sem juros embutidos", description: "Evite linhas de crédito náutico com custo efetivo alto.", highlight: "Economia real" },
      { title: "Novo ou usado", description: "Conforme regras do grupo, você pode mirar diferentes tipos de embarcação.", highlight: "Flexibilidade" },
      { title: "Planejamento longo", description: "Prazos que cabem no orçamento do marinheiro de fim de semana ao velejador.", highlight: "Prazo flexível" },
      { title: "Assessoria completa", description: "Da simulação ao uso da carta, time Lacosta ao seu lado.", highlight: "Suporte dedicado" },
      { title: "Lance inteligente", description: "Quer antecipar? Avaliamos lance com você.", highlight: "Contemplação" },
      { title: "100% regulamentado", description: "Consórcio supervisionado pelo Banco Central.", highlight: "Segurança" },
    ],
    faqs: [
      { question: "Consórcio cobre jet ski e lancha?", answer: "Dependendo do grupo e do valor da carta, sim. Na análise definimos o produto compatível com o bem desejado." },
      { question: "Preciso comprovar uso da embarcação?", answer: "A documentação segue exigências da administradora na contemplação e liberação do crédito. Orientamos em cada etapa." },
      { question: "Posso comprar de particular?", answer: "Quando permitido pelo regulamento da cota, a carta pode ser usada com vendedores credenciados ou conforme regra do produto. Confirme com nosso consultor." },
      { question: "Há seguro obrigatório no consórcio?", answer: "Taxas e seguros variam por administradora. Tudo consta no contrato, sem juros de financiamento." },
    ],
    sectionOrder: ["problem-solution", "stats", "features", "comparison", "steps", "benefits", "faq", "cross-sell"],
    statsHighlight: [
      { value: "R$ 40 mil", label: "Economia média", description: "Comparado a financiamento náutico tradicional" },
      { value: "Sem entrada", label: "Diferencial", description: "Comece pagando apenas a primeira parcela do grupo" },
      { value: "+R$ 200 mil", label: "Cartas disponíveis", description: "Valores que alcançam lanchas e veleiros de porte" },
    ],
    featureTitle: "Tipos de embarcação",
    featureSubtitle: "A carta se adapta ao seu sonho náutico",
    featureCards: [
      { title: "Lancha", description: "De passeio ou esportiva, nova ou seminova conforme grupo." },
      { title: "Barco a motor", description: "Pesca esportiva, lazer ou trabalho marítimo." },
      { title: "Jet ski", description: "Diversão na água com planejamento financeiro sólido." },
      { title: "Veleiro", description: "Para quem busca liberdade nos mares com vela." },
    ],
  },

  servicos: {
    slug: "consorcio-servicos",
    name: "Consórcio de Serviços",
    shortName: "Serviços",
    heroTitle: "Consórcio de Serviços",
    heroAccent: "Para o Seu Negócio",
    heroSubtitle:
      "Crédito para equipar o escritório, capital de giro autorizado, tecnologia e expansão sem juros de empréstimo tradicional.",
    heroImage: "/items/servicos.png",
    metaTitle: "Consórcio de Serviços Sem Juros | Empresas e Liberdade Profissional",
    metaDescription:
      "Consórcio de serviços Servopa e Rodobens: equipamentos, estrutura e metas profissionais sem juros. Simule na Lacosta.",
    ogTitle: "Consórcio de Serviços | Lacosta Consórcios",
    ogDescription: "Expanda seu negócio ou estrutura profissional com consórcio sem juros.",
    calculatorCategory: "servicos",
    avgSaving: "R$ 35.000",
    introTitle: "Consórcio de serviços faz sentido para quem?",
    introText:
      "Profissionais liberais, MEIs e empresas que precisam de equipamentos, reforma de espaço ou aquisições pontuais podem usar o consórcio em vez de capital de giro caro. A carta contemplada vira recurso para investir sem juros compostos.",
    problemTitle: "Empréstimo para empresa sai caro",
    problemText:
      "Linhas PJ com juros altos e garantias pesadas encarecem qualquer expansão. No cartão corporativo, o rotativo destrói margem.",
    solutionTitle: "Carta de consórcio para investir na operação",
    solutionText:
      "Você disciplina poupança via parcelas do grupo e, ao ser contemplado, recebe o valor para aplicar no que o negócio precisa, segundo o produto contratado.",
    comparison: [
      { label: "Crédito R$ 100.000", financing: "Juros PJ + taxas", consortium: "Taxa admin", winner: "consortium" },
      { label: "Fluxo de caixa", financing: "Parcela oscila com juros", consortium: "Parcela fixa do grupo", winner: "consortium" },
      { label: "Garantias", financing: "Muitas vezes sim", consortium: "Conforme produto", winner: "tie" },
      { label: "Uso do valor", financing: "Livre às vezes", consortium: "Conforme segmento serviço", winner: "tie" },
      { label: "Custo em 5 anos", financing: "Muito maior", consortium: "Menor", winner: "consortium" },
      { label: "Regulamentação", financing: "Varia", consortium: "Banco Central", winner: "consortium" },
    ],
    comparisonNote: "Comparativo ilustrativo. Segmento de serviços tem regras específicas por administradora.",
    steps: [
      { title: "Mapeamos a necessidade", description: "Equipamento, reforma, tecnologia: o que você precisa financiar com a carta?" },
      { title: "Simulação", description: "Montamos valor de crédito e prazo coerentes com sua capacidade." },
      { title: "Adesão ao grupo", description: "Formalização e participação nas assembleias." },
      { title: "Aplicação do crédito", description: "Após contemplação, uso do crédito conforme regulamento do serviço." },
    ],
    theme: {
      accent: "#475569",
      accentLight: "#94A3B8",
      accentRgb: "71,85,105",
      gradient: "linear-gradient(135deg, #334155 0%, #475569 100%)",
      darkBg: "linear-gradient(180deg, #0F172A 0%, #1E293B 50%, #0F172A 100%)",
      benefitsLayout: "list",
      comparisonStyle: "cards",
      stepsStyle: "timeline",
    },
    ctaHeadline: "Quero expandir meu negócio sem juros bancários",
    ctaSub: "Descubra o crédito ideal para equipamentos, tecnologia ou reforma do espaço.",
    ctaStats: "Simular crédito para meu negócio",
    ctaFeatures: "O que seu negócio precisa agora? Veja a carta ideal.",
    ctaSteps: "Começar a estruturar meu negócio",
    benefits: [
      { title: "Foco no crescimento", description: "Menos custo financeiro, mais recurso para reinvestir.", highlight: "Margem preservada" },
      { title: "Para diversos segmentos", description: "Conceitos adaptados a diferentes ramos de serviço autorizados.", highlight: "Versatilidade" },
      { title: "Planejamento", description: "Combine prazo da carta com metas do negócio.", highlight: "Estratégia" },
      { title: "Sem rotativo", description: "Saia do cartão corporativo quando o caso permitir migração para consórcio.", highlight: "Disciplina" },
      { title: "Consultoria", description: "Consultores Lacosta entendem Servopa e Rodobens.", highlight: "Especialistas" },
      { title: "Contemplação", description: "Sorteio e lance para acelerar quando fizer sentido.", highlight: "Flexível" },
    ],
    faqs: [
      { question: "MEI pode fazer consórcio de serviços?", answer: "Sim, pessoa física e jurídica podem aderir conforme elegibilidade e análise da administradora." },
      { question: "O que posso comprar com a carta?", answer: "Depende do grupo de serviços contratado: pode incluir equipamentos, mobiliário ou outros usos previstos no regulamento." },
      { question: "É parecido com microcrédito?", answer: "Não. Consórcio não é empréstimo com juros; é grupo de consorciados administrado conforme normas do Bacen." },
    ],
    sectionOrder: ["stats", "features", "problem-solution", "comparison", "benefits", "steps", "faq", "cross-sell"],
    statsHighlight: [
      { value: "R$ 35 mil", label: "Economia em crédito PJ", description: "Comparado a empréstimo empresarial com juros altos" },
      { value: "Bacen", label: "100% regulamentado", description: "Supervisionado pelo Banco Central do Brasil" },
      { value: "PF e PJ", label: "Acesso flexível", description: "Pessoa física e jurídica podem participar" },
    ],
    featureTitle: "Para cada necessidade do negócio",
    featureSubtitle: "Estruture a operação sem comprometer o fluxo de caixa",
    featureCards: [
      { title: "Equipamentos", description: "Máquinas, ferramentas e tecnologia para produção." },
      { title: "Tecnologia", description: "Servidores, software e infraestrutura digital." },
      { title: "Mobiliário profissional", description: "Cadeiras, mesas, consultórios e ambientação." },
      { title: "Reforma de espaço", description: "Adequação de ponto comercial ou escritório." },
      { title: "Expansão", description: "Abra filial ou amplie a estrutura existente." },
      { title: "Frota empresarial", description: "Veículos para entrega, representação ou equipe." },
    ],
  },

  agronegocio: {
    slug: "consorcio-agronegocio",
    name: "Consórcio para Agronegócio",
    shortName: "Agronegócio",
    heroTitle: "Consórcio no Agronegócio",
    heroAccent: "Campo e Máquinas",
    heroSubtitle:
      "Trator, colheitadeira, pivô, benfeitorias rurais e imóveis do agronegócio com carta sem juros de financiamento rural tradicional.",
    heroImage: "/items/agro.png",
    metaTitle: "Consórcio Agrícola Sem Juros | Máquinas e Rural | Lacosta",
    metaDescription:
      "Consórcio para agronegócio: máquinas, equipamentos e projetos rurais sem juros. Servopa e Rodobens com assessoria Lacosta.",
    ogTitle: "Consórcio Agronegócio | Lacosta Consórcios",
    ogDescription: "Crédito rural via consórcio para modernizar sua produção.",
    calculatorCategory: "agronegocio",
    avgSaving: "R$ 80.000",
    introTitle: "Por que produtor escolhe consórcio?",
    introText:
      "O custo de financiar maquinário ou benfeitorias com juros pode consumir a margem da safra. No consórcio, você programa a entrada de crédito com parcelas conhecidas e taxa de administração, sem juros compostos de banco.",
    problemTitle: "Juros corroem a margem do produtor",
    problemText:
      "Renovação de frota ou irrigação financiada pode significar anos pagando juros que competem com preço da commodity.",
    solutionTitle: "Consórcio libera crédito com lógica de grupo",
    solutionText:
      "Você integra grupo alinhado ao agronegócio, paga parcelas e concorre à carta para aplicar no investimento rural permitido pelo produto.",
    comparison: [
      { label: "Investimento R$ 300.000", financing: "Financiamento rural", consortium: "Consórcio", winner: "tie" },
      { label: "Juros", financing: "Sim (elevados)", consortium: "Não há juros*", winner: "consortium" },
      { label: "Taxa admin", financing: "-", consortium: "Contratada", winner: "tie" },
      { label: "Carência / fluxo safra", financing: "Às vezes", consortium: "Conforme grupo", winner: "tie" },
      { label: "Total pago (longo prazo)", financing: "Maior", consortium: "Tipicamente menor", winner: "consortium" },
      { label: "Planejamento", financing: "Revisão constante", consortium: "Parcela definida", winner: "consortium" },
    ],
    comparisonNote: "*Consórcio não tem juros; inclui taxa de administração. Compare sempre o custo efetivo total.",
    steps: [
      { title: "Diagnóstico", description: "Conte o que precisa: máquina, estrutura, área." },
      { title: "Simulação rural", description: "Montamos valor e prazo compatíveis com seu fluxo." },
      { title: "Grupo certo", description: "Indicação de produto Servopa ou Rodobens para agronegócio." },
      { title: "Contemplação e aquisição", description: "Uso da carta conforme regulamento do investimento rural." },
    ],
    theme: {
      accent: "#16A34A",
      accentLight: "#4ADE80",
      accentRgb: "22,163,74",
      gradient: "linear-gradient(135deg, #15803D 0%, #16A34A 100%)",
      darkBg: "linear-gradient(180deg, #052E16 0%, #14532D 50%, #052E16 100%)",
      benefitsLayout: "grid",
      comparisonStyle: "table",
      stepsStyle: "horizontal",
    },
    ctaHeadline: "Quero modernizar a produção sem juros rurais",
    ctaSub: "Simule a carta para trator, irrigação ou benfeitoria e veja a parcela em 30 segundos.",
    ctaStats: "Calcular minha economia no campo",
    ctaFeatures: "O que sua fazenda precisa? Simule o investimento.",
    ctaSteps: "Iniciar meu planejamento agrícola",
    benefits: [
      { title: "Máquinas e equipamentos", description: "Linhas voltadas a fortalecer a produção.", highlight: "Produtividade" },
      { title: "Sem juros", description: "Lógica de consórcio, não de spread bancário.", highlight: "Economia" },
      { title: "Assessoria especializada", description: "Entendemos linguagem do campo e dos números.", highlight: "Lacosta" },
      { title: "Prazos estendidos", description: "Grupos com prazos que acompanham o investimento.", highlight: "Capacidade" },
      { title: "Lance", description: "Quando o calendário agrícola aperta, avaliamos lance.", highlight: "Antecipação" },
      { title: "Bacen", description: "Modalidade regulamentada e supervisionada.", highlight: "Segurança" },
    ],
    faqs: [
      { question: "Consórcio cobre trator usado?", answer: "Depende do regulamento do grupo e da administradora. Avaliamos caso a caso." },
      { question: "Produtor pessoa física pode?", answer: "Sim, quando atende critérios da administradora e perfil do grupo." },
      { question: "Substitui financiamento BNDES?", answer: "São produtos diferentes. O consórcio pode ser alternativa ou complemento conforme estratégia; nossa equipe orienta." },
    ],
    sectionOrder: ["features", "stats", "problem-solution", "comparison", "steps", "benefits", "faq", "cross-sell"],
    statsHighlight: [
      { value: "R$ 80 mil", label: "Economia vs rural", description: "Comparado a financiamento rural com juros elevados" },
      { value: "Sem safra", label: "Comprometida", description: "Parcelas planejadas fora do calendário de colheita" },
      { value: "Todo Brasil", label: "Cobertura nacional", description: "Grupos disponíveis para produtores de qualquer região" },
    ],
    featureTitle: "Do trator à irrigação",
    featureSubtitle: "Cada investimento rural com planejamento de consórcio",
    featureCards: [
      { title: "Trator e colheitadeira", description: "Máquinas pesadas para plantio e colheita produtiva." },
      { title: "Implementos agrícolas", description: "Grade, plantadeira, pulverizador e mais." },
      { title: "Sistema de irrigação", description: "Pivô central, gotejamento e aspersão." },
      { title: "Benfeitorias rurais", description: "Galpão, silo, curral e infraestrutura da propriedade." },
      { title: "Imóvel rural", description: "Compre terra para expandir a área produtiva." },
      { title: "Caminhão de carga", description: "Transporte próprio para escoar a produção." },
    ],
  },

  educacao: {
    slug: "consorcio-educacao",
    name: "Consórcio para Educação",
    shortName: "Educação",
    heroTitle: "Consórcio para Educação",
    heroAccent: "Sem Juros",
    heroSubtitle:
      "Cursos técnicos, graduação, pós, intercâmbio e formaturas: planeje mensalidades e pacotes com consórcio.",
    heroImage: "/items/educacao.png",
    metaTitle: "Consórcio para Educação Sem Juros | Cursos e Formatura | Lacosta",
    metaDescription:
      "Consórcio educacional sem juros para cursos, faculdade e eventos. Simule grátis com Servopa e Rodobens via Lacosta.",
    ogTitle: "Consórcio para Educação | Lacosta Consórcios",
    ogDescription: "Invista em estudos com parcelas de consórcio, sem juros de crédito estudantil caro.",
    calculatorCategory: "educacao",
    avgSaving: "R$ 18.000",
    introTitle: "Educação planejada vale mais",
    introText:
      "Financiar curso no cartão ou com empréstimos pessoais encarece demais o investimento em carreira. O consórcio permite acumular a carta e quitar instituições ou pacores conforme o produto educacional disponível.",
    problemTitle: "Crédito educacional e cartão pesam",
    problemText:
      "Parcelas com juros podem durar mais que o próprio curso, travando o orçamento familiar por anos.",
    solutionTitle: "Consórcio distribui custo com transparência",
    solutionText:
      "Você define um valor de crédito alinhado à meta educacional e participa do grupo até a contemplação.",
    comparison: [
      { label: "Pacote R$ 40.000", financing: "Cartão / empréstimo", consortium: "Consórcio", winner: "tie" },
      { label: "Juros", financing: "Sim", consortium: "Não (taxa admin)", winner: "consortium" },
      { label: "Prestação mensal", financing: "Pode subir", consortium: "Linha do grupo", winner: "consortium" },
      { label: "Planejamento familiar", financing: "Estresse", consortium: "Previsível", winner: "consortium" },
      { label: "Múltiplos dependentes", financing: "Limite afunila", consortium: "Projeto por cota", winner: "consortium" },
      { label: "Contemplação", financing: "N/A", consortium: "Sorteio / lance", winner: "consortium" },
    ],
    comparisonNote: "Exemplo ilustrativo. Produtos educacionais seguem regulamentos específicos.",
    steps: [
      { title: "Meta educacional", description: "Curso, faculdade ou evento: estimamos o valor alvo." },
      { title: "Simulação", description: "Encaixamos parcela no orçamento familiar." },
      { title: "Adesão", description: "Contratação do consórcio educacional adequado." },
      { title: "Pagamentos", description: "Após contemplação, uso do crédito conforme regras da administradora." },
    ],
    theme: {
      accent: "#D97706",
      accentLight: "#FBBF24",
      accentRgb: "217,119,6",
      gradient: "linear-gradient(135deg, #B45309 0%, #D97706 100%)",
      darkBg: "linear-gradient(180deg, #271300 0%, #451A03 50%, #271300 100%)",
      benefitsLayout: "bento",
      comparisonStyle: "cards",
      stepsStyle: "timeline",
    },
    ctaHeadline: "Quero investir na educação sem dívida de cartão",
    ctaSub: "Descubra a parcela para graduação, intercâmbio ou formatura em 30 segundos.",
    ctaStats: "Ver quanto economizo na educação",
    ctaFeatures: "Qual investimento educacional você planeja? Simule agora.",
    ctaSteps: "Planejar o futuro da família agora",
    benefits: [
      { title: "Carreira e futuro", description: "Invista em certificações e graduação com método estruturado.", highlight: "Longo prazo" },
      { title: "Sem sustos no cartão", description: "Evite rotativo para pagar mensalidade.", highlight: "Controle" },
      { title: "Formatura e eventos", description: "Planeje festas e viagens de formatura com carta.", highlight: "Momentos únicos" },
      { title: "Assessoria", description: "Lacosta alinha expectativa com produto certo.", highlight: "Orientação" },
      { title: "Grupos tradicionais", description: "Servopa e Rodobens.", highlight: "Confiança" },
      { title: "Lance", description: "Antecipe se a data da matrícula apertar.", highlight: "Opcional" },
    ],
    faqs: [
      { question: "Consórcio paga mensalidade direto na faculdade?", answer: "O fluxo depende de como o crédito é liberado após contemplação e das regras do grupo. Explicamos o passo a passo na contratação." },
      { question: "Serve para intercâmbio?", answer: "Quando o valor e o uso forem compatíveis com o produto contratado, sim. Valide com nosso consultor." },
    ],
    sectionOrder: ["problem-solution", "stats", "features", "comparison", "steps", "benefits", "faq", "cross-sell"],
    statsHighlight: [
      { value: "R$ 18 mil", label: "Economia vs cartão", description: "Sem juros rotativos de parcelamento convencional" },
      { value: "Sem rotativo", label: "Zero juros", description: "Nenhum custo surpresa no fim do mês" },
      { value: "Família toda", label: "Múltiplas cotas", description: "Cada membro pode ter seu plano educacional" },
    ],
    featureTitle: "Investimento em cada fase da vida",
    featureSubtitle: "Da graduação ao MBA, cada etapa com planejamento sem juros",
    featureCards: [
      { title: "Graduação e pós", description: "Mensalidades de universidade ou especialização." },
      { title: "Intercâmbio", description: "Estude fora com crédito planejado e sem juros." },
      { title: "Cursos técnicos", description: "Capacitação profissional para o mercado de trabalho." },
      { title: "Formatura e eventos", description: "Festas, viagens e celebrações inesquecíveis." },
      { title: "MBA e especialização", description: "Invista na carreira executiva com parcelas organizadas." },
      { title: "Ensino infantil", description: "Planeje escola particular dos filhos desde cedo." },
    ],
  },

  saude: {
    slug: "consorcio-saude",
    name: "Consórcio para Saúde",
    shortName: "Saúde",
    heroTitle: "Consórcio para Saúde",
    heroAccent: "Procedimentos e Bem-Estar",
    heroSubtitle:
      "Cirurgias eletivas, odontologia avançada, tratamentos particulares: crédito sem juros com planejamento humano.",
    heroImage: "/items/saude.png",
    metaTitle: "Consórcio para Saúde Sem Juros | Procedimentos | Lacosta",
    metaDescription:
      "Consórcio de saúde sem juros para procedimentos e tratamentos. Carta Servopa e Rodobens com assessoria Lacosta.",
    ogTitle: "Consórcio para Saúde | Lacosta Consórcios",
    ogDescription: "Cuide da saúde com parcelas de consórcio, sem financiamento abusivo.",
    calculatorCategory: "saude",
    avgSaving: "R$ 22.000",
    introTitle: "Saúde não pode esperar o cartão",
    introText:
      "Muitos pacientes recorrem ao limite do cartão ou empréstimos caros para operar ou tratar. O consórcio oferece caminho regulamentado, com taxa de administração conhecida e sem juros, para montar o valor do tratamento.",
    problemTitle: "Dívidas médicas crescem rápido",
    problemText:
      "Um procedimento parcelado com juros pode dobrar o custo emocional e financeiro da família.",
    solutionTitle: "Consórcio organiza o tratamento",
    solutionText:
      "Você planeja, paga parcelas do grupo e usa a carta contemplada conforme rede e regra do produto de saúde/serviços.",
    comparison: [
      { label: "Tratamento R$ 50.000", financing: "Empréstimo / cartão", consortium: "Consórcio", winner: "tie" },
      { label: "Juros", financing: "Altos", consortium: "Inexistentes (taxa admin)", winner: "consortium" },
      { label: "Psicológico", financing: "Pressão", consortium: "Plano claro", winner: "consortium" },
      { label: "Credenciamento", financing: "Qualquer", consortium: "Conforme grupo", winner: "tie" },
      { label: "Prazo", financing: "Curto ou longo", consortium: "Definido no grupo", winner: "tie" },
      { label: "Suporte Lacosta", financing: "Você sozinho", consortium: "Consultoria", winner: "consortium" },
    ],
    comparisonNote: "Exemplo ilustrativo. Produtos de saúde seguem tabelas das administradoras.",
    steps: [
      { title: "Entendemos a necessidade", description: "Procedimento e ordem de grandeza de custo." },
      { title: "Simulação", description: "Crédito e prazo alinhados ao orçamento." },
      { title: "Grupo de serviços / saúde", description: "Indicação formal do produto." },
      { title: "Contemplação e uso", description: "Liberação conforme regulamento para tratamento." },
    ],
    theme: {
      accent: "#059669",
      accentLight: "#34D399",
      accentRgb: "5,150,105",
      gradient: "linear-gradient(135deg, #047857 0%, #059669 100%)",
      darkBg: "linear-gradient(180deg, #022C22 0%, #064E3B 50%, #022C22 100%)",
      benefitsLayout: "list",
      comparisonStyle: "table",
      stepsStyle: "timeline",
    },
    ctaHeadline: "Quero cuidar da saúde sem pressão financeira",
    ctaSub: "Simule o crédito para cirurgia, tratamento ou procedimento sem juros.",
    ctaStats: "Calcular minha economia em saúde",
    ctaFeatures: "Qual tratamento você precisa? Veja o plano ideal.",
    ctaSteps: "Iniciar meu planejamento de saúde",
    benefits: [
      { title: "Dignidade no cuidado", description: "Menos pressão financeira na hora de decidir pelo tratamento.", highlight: "Tranquilidade" },
      { title: "Odontologia e procedimentos", description: "Linhas que atendem diversos casos autorizados.", highlight: "Amplitude" },
      { title: "Transparente", description: "Taxa de administração explícita, sem juros escondidos.", highlight: "Clareza" },
      { title: "Time humano", description: "Atendimento com empatia e experiência.", highlight: "Lacosta" },
      { title: "Administradoras sólidas", description: "Servopa e Rodobens.", highlight: "Tradição" },
      { title: "Lance", description: "Para quando o tempo médico não pode esperar.", highlight: "Urgência planejada" },
    ],
    faqs: [
      { question: "Todo hospital aceita consórcio?", answer: "O uso depende de credenciamento e regras da administradora. Validamos com você antes de contratar." },
      { question: "Substitui plano de saúde?", answer: "Não. Consórcio é instrumento de aquisição de crédito, não seguro saúde." },
    ],
    sectionOrder: ["stats", "problem-solution", "features", "comparison", "benefits", "steps", "faq", "cross-sell"],
    statsHighlight: [
      { value: "R$ 22 mil", label: "Economia média", description: "Comparado a empréstimo pessoal ou rotativo de cartão" },
      { value: "0", label: "Pressão financeira", description: "Planejamento que respeita seu momento e orçamento" },
      { value: "Rede", label: "Credenciada", description: "Parceiros validados pela administradora do grupo" },
    ],
    featureTitle: "Cuidados que o consórcio alcança",
    featureSubtitle: "Da cirurgia ao tratamento prolongado, tudo com planejamento",
    featureCards: [
      { title: "Cirurgias eletivas", description: "Procedimentos planejados com antecedência e segurança." },
      { title: "Odontologia avançada", description: "Implantes, próteses e reconstrução dentária completa." },
      { title: "Tratamentos prolongados", description: "Fisioterapia, reabilitação e acompanhamento contínuo." },
      { title: "Reabilitação", description: "Programas especializados de recuperação funcional." },
      { title: "Procedimentos especializados", description: "Oftalmologia, ortopedia e tratamentos de ponta." },
      { title: "Exames de alto custo", description: "Ressonância, PET-scan e diagnósticos avançados." },
    ],
  },

  reforma: {
    slug: "consorcio-reforma",
    name: "Consórcio para Reforma",
    shortName: "Reforma",
    heroTitle: "Consórcio para Reforma",
    heroAccent: "Casa e Obra",
    heroSubtitle:
      "Amplie, modernize ou construja com carta de crédito sem juros. Obra nos seus termos, com parcelas organizadas.",
    heroImage: "/items/reforma.png",
    metaTitle: "Consórcio para Reforma Sem Juros | Casa e Ampliação | Lacosta",
    metaDescription:
      "Reforma e construção com consórcio sem juros. Materiais, mão de obra e projeto com Servopa e Rodobens. Lacosta assessora.",
    ogTitle: "Consórcio para Reforma | Lacosta Consórcios",
    ogDescription: "Transforme seu imóvel sem financiamento caro de reforma.",
    calculatorCategory: "reforma",
    avgSaving: "R$ 28.000",
    introTitle: "Reforma sem susto no bolso",
    introText:
      "Muita gente estoura o limite do cartão com materiais e mão de obra. O consórcio de reforma ou linhas afins permite acumular o valor da carta com custo previsível, sem juros de empréstimo imobiliário complementar ou crédito pessoal caro.",
    problemTitle: "Obra e cartão não combinam",
    problemText:
      "A obra sempre custa um pouco mais. Com juros do cartão, o estouro vira dívida de anos.",
    solutionTitle: "Carta para reformar com disciplina",
    solutionText:
      "Você entra no grupo, paga parcelas fixas do consórcio e, contemplado, aplica o crédito na reforma conforme permitido pelo grupo.",
    comparison: [
      { label: "Obra R$ 80.000", financing: "Cartão + empréstimo", consortium: "Consórcio", winner: "tie" },
      { label: "Juros", financing: "Sim, altos", consortium: "Não", winner: "consortium" },
      { label: "Compatível com imóvel próprio", financing: "Sim", consortium: "Sim (regras)", winner: "tie" },
      { label: "Negociação à vista na obra", financing: "Difícil", consortium: "Com carta, melhor", winner: "consortium" },
      { label: "Previsibilidade", financing: "Baixa", consortium: "Alta", winner: "consortium" },
      { label: "Regulamentação Bacen", financing: "Varia", consortium: "Sim", winner: "consortium" },
    ],
    comparisonNote: "Ilustrativo. Produtos de reforma e serviço seguem regulamento de cada administradora.",
    steps: [
      { title: "Orçamento da obra", description: "Levantamos valor aproximado de reforma ou ampliação." },
      { title: "Simulação", description: "Definimos carta e prazo compatíveis com sua obra." },
      { title: "Adesão ao grupo", description: "Contratação e assembleias." },
      { title: "Execução", description: "Após contemplação, aplicação do crédito na reforma conforme produto." },
    ],
    theme: {
      accent: "#EA580C",
      accentLight: "#FB923C",
      accentRgb: "234,88,12",
      gradient: "linear-gradient(135deg, #C2410C 0%, #EA580C 100%)",
      darkBg: "linear-gradient(180deg, #290E00 0%, #431407 50%, #290E00 100%)",
      benefitsLayout: "grid",
      comparisonStyle: "cards",
      stepsStyle: "horizontal",
    },
    ctaHeadline: "Quero reformar meu imóvel sem juros escondidos",
    ctaSub: "Descubra a carta ideal para ampliação, modernização ou construção em 30 segundos.",
    ctaStats: "Ver quanto economizo na reforma",
    ctaFeatures: "Qual projeto de reforma você tem em mente? Simule o valor.",
    ctaSteps: "Começar meu projeto de reforma",
    benefits: [
      { title: "Obra planejada", description: "Menos improviso financeiro no meio da construção.", highlight: "Controle" },
      { title: "Materiais e mão de obra", description: "Crédito voltado ao que a obra precisa, conforme grupo.", highlight: "Completo" },
      { title: "Sem juros", description: "Apost na taxa de administração, não em juros rotativos.", highlight: "Economia" },
      { title: "Assessoria", description: "Lacosta ajuda do início ao uso da carta.", highlight: "Suporte" },
      { title: "Grupos fortes", description: "Servopa e Rodobens.", highlight: "Tradição" },
      { title: "Lance", description: "Para antecipar se a data da obra apertar.", highlight: "Opcional" },
    ],
    faqs: [
      { question: "Consórcio de reforma cobre apenas material?", answer: "Depende do produto. Alguns grupos permitem combinações previstas em regulamento. Validamos na simulação." },
      { question: "Posso reformar imóvel financiado?", answer: "Muitas vezes sim para benfeitorias; há nuances jurídicas e de produto. Nossa equipe orienta." },
    ],
    sectionOrder: ["features", "problem-solution", "stats", "comparison", "steps", "benefits", "faq", "cross-sell"],
    statsHighlight: [
      { value: "R$ 28 mil", label: "Economia na obra", description: "Comparado a empréstimo pessoal para reforma" },
      { value: "Obra completa", label: "Materiais + mão de obra", description: "Carta que cobre todo o escopo do projeto" },
      { value: "À vista", label: "Poder de negociação", description: "Negocie material de construção com desconto" },
    ],
    featureTitle: "Cada projeto, uma possibilidade",
    featureSubtitle: "Da ampliação ao acabamento premium, seu imóvel transformado",
    featureCards: [
      { title: "Ampliação", description: "Mais um quarto, edícula ou área de lazer." },
      { title: "Modernização", description: "Elétrica, hidráulica e acabamentos atualizados." },
      { title: "Construção nova", description: "Inicie obra do zero no seu terreno." },
      { title: "Acabamento premium", description: "Porcelanato, marcenaria planejada e iluminação." },
      { title: "Paisagismo", description: "Jardim, piscina e área gourmet externa." },
      { title: "Reforma comercial", description: "Atualize loja, escritório ou consultório." },
    ],
  },

};
